apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-spa-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ms-spa
  template:
    metadata:
      labels:
        app: ms-spa
    spec:
      containers:
      - image: docker.io/jmartinezblanco/metaspa
        imagePullPolicy: Always
        name: ms-spa-container
        resources: {}
